[package]
name = "gdk4-wayland"
version = "0.1.0"
authors = ["The Gtk-rs Project Developers"]
edition = "2018"
build = "build.rs"

[features]
purge-lgpl-docs = ["gtk-rs-lgpl-docs"]
embed-lgpl-docs = ["gtk-rs-lgpl-docs"]
dox = ["ffi/dox"]

[package.metadata.docs.rs]
features = ["dox", "embed-lgpl-docs"]

[build-dependencies.gtk-rs-lgpl-docs]
version = "0.1.3"
optional = true
git = "https://github.com/gtk-rs/lgpl-docs"

[dependencies]
libc = "0.2"
wayland-client = { version = "0.28", features = ["use_system_lib"] }

[dependencies.glib]
git = "https://github.com/gtk-rs/gtk-rs"
features = ["v2_66"]

[dependencies.gio]
git = "https://github.com/gtk-rs/gtk-rs"
features = ["v2_66"]

[dependencies.gdk]
path = "../gdk4"
package = "gdk4"

[dependencies.ffi]
path = "./sys"
package = "gdk4-wayland-sys"

[dev-dependencies]
gir-format-check = "^0.1"
