[package]
authors = ["The gtk-rs Project Developers"]
description = "Rust bindings of the GDK 4 Wayland library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/latest/docs/gdk4_wayland/"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gdk4", "gdk4-wayland", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gdk4-wayland"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.3.0"

[features]
v4_4 = ["ffi/v4_4", "khronos-egl", "xkb"]
dox = ["ffi/dox", "khronos-egl", "xkb"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
ffi = {path = "./sys", package = "gdk4-wayland-sys"}
gdk = {path = "../gdk4", package = "gdk4"}
gio = {git = "https://github.com/gtk-rs/gtk-rs-core", features = ["v2_66"]}
glib = {git = "https://github.com/gtk-rs/gtk-rs-core", features = ["v2_66"]}
libc = "0.2"
wayland-client = {version = "0.28", features = ["use_system_lib"]}
khronos-egl = {version = "4.1.0", optional = true}
xkb = {version = "0.2.1", optional = true}

[dev-dependencies]
gir-format-check = "^0.1"
