[package]
authors = ["The gtk-rs Project Developers"]
description = "Rust bindings of the GDK 4 Wayland library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/latest/docs/gdk4_wayland/"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gdk4", "gdk4-wayland", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gdk4-wayland"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.1.0"

[features]
dox = ["ffi/dox"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
ffi = {package = "gdk4-wayland-sys", version = "0.1.0"}
gdk = {package = "gdk4", version = "0.1.0"}
gio = {features = ["v2_66"], version = "0.14.0"}
glib = {features = ["v2_66"], version = "0.14.0"}
libc = "0.2"
wayland-client = {version = "0.28", features = ["use_system_lib"]}

[dev-dependencies]
gir-format-check = "^0.1"
