[options]
girs_dir = "gir-files"
library = "GdkWayland"
version = "4.0"
min_cfg_version = "4.0.0"
target_path = "."
work_mode = "normal"
single_version_file = true
generate_safety_asserts = true
deprecate_by_min_version = true

generate = [
    "GdkWayland.WaylandGLContext",
    "GdkWayland.WaylandPopup",
    "GdkWayland.WaylandToplevel",
    "GdkWayland.WaylandToplevelExported"
]

manual = [
    "Gdk.Device",
    "Gdk.Display",
    "Gdk.DrawContext",
    "Gdk.GLContext",
    "Gdk.Monitor",
    "Gdk.Popup",
    "Gdk.Seat",
    "Gdk.Surface",
    "Gdk.Toplevel",
]

[[object]]
name = "GdkWayland.WaylandDevice"
status = "generate"
manual_traits = ["WaylandDeviceManualExt"]
    [[object.function]]
    name = "get_wl_keyboard"
    manual = true
    [[object.function]]
    name = "get_wl_pointer"
    manual = true
    [[object.function]]
    name = "get_wl_seat"
    manual = true

[[object]]
name = "GdkWayland.WaylandDisplay"
status = "generate"
manual_traits = ["WaylandDisplayManualExt"]
    [[object.function]]
    name = "get_wl_compositor"
    manual = true
    [[object.function]]
    name = "get_wl_display"
    manual = true

[[object]]
name = "GdkWayland.WaylandMonitor"
status = "generate"
manual_traits = ["WaylandMonitorManualExt"]
    [[object.function]]
    name = "get_wl_output"
    manual = true

[[object]]
name = "GdkWayland.WaylandSeat"
status = "generate"
manual_traits = ["WaylandSeatManualExt"]
    [[object.function]]
    name = "get_wl_seat"
    manual = true

[[object]]
name = "GdkWayland.WaylandSurface"
status = "generate"
manual_traits = ["WaylandSurfaceManualExt"]
    [[object.function]]
    name = "get_wl_surface"
    manual = true
