dist: xenial
language: rust
matrix:
  include:
    - os: linux
      rust: nightly
      env: GTK=3.96 FEATURES=
    - os: linux
      rust: beta
      env: GTK=3.96 FEATURES=
    - os: linux
      rust: 1.31.0
      env: GTK=3.96 FEATURES=
addons:
  apt:
    packages:
    - libgtk-3-dev
    - libmount-dev
script:
  - rustc --version
  - if [ "$TRAVIS_RUST_VERSION" == "nightly" ] && [ "$GTK" == "3.96" ]; then
    make regen_check;
    fi
  - ./check_init_asserts
  - cargo doc --features "dox,embed-lgpl-docs"
  - cargo test --features "$FEATURES,embed-lgpl-docs"
  # catch any sneaked in lgpl docs
  - cargo build --features "$FEATURES,purge-lgpl-docs" --jobs 1
  - git diff -R --exit-code
  - rustc --version
  - mkdir .cargo
  - echo 'paths = ["."]' > .cargo/config
  - git clone -q --depth 50 https://github.com/sfanxiang/gtk-rs-examples4 _examples
  - cd _examples
  - ./build_travis.sh
