[package]
authors = ["The gtk-rs Project Developers"]
description = "Rust bindings of the GDK 4 library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/latest/docs/gdk4/"
edition = "2018"
homepage = "https://gtk-rs.org/"
keywords = ["gdk", "gdk4", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gdk4"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.1.0"

[lib]
name = "gdk4"

[features]
dox = ["ffi/dox", "glib/dox", "gio/dox", "gdk-pixbuf/dox", "cairo-rs/dox", "pango/dox"]
v4_2 = ["ffi/v4_2"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
bitflags = "1.0"
cairo-rs = {git = "https://github.com/gtk-rs/gtk-rs-core"}
ffi = {package = "gdk4-sys", path = "./sys"}
gdk-pixbuf = {git = "https://github.com/gtk-rs/gtk-rs-core"}
gio = {git = "https://github.com/gtk-rs/gtk-rs-core", features = ["v2_66"]}
glib = {git = "https://github.com/gtk-rs/gtk-rs-core", features = ["v2_66"]}
libc = "0.2"
pango = {git = "https://github.com/gtk-rs/gtk-rs-core", features = ["v1_46"]}

[dev-dependencies]
gir-format-check = "^0.1"
