[package]
authors = ["The gtk-rs Project Developers"]
description = "Rust bindings of the GDK 4 library"
documentation = "https://gtk-rs.org/gtk4-rs/stable/latest/docs/gdk4/"
edition = "2021"
homepage = "https://gtk-rs.org/"
keywords = ["gdk", "gdk4", "gtk-rs", "gnome", "GUI"]
license = "MIT"
name = "gdk4"
readme = "README.md"
repository = "https://github.com/gtk-rs/gtk4-rs"
version = "0.4.10"
rust-version = "1.56"

[lib]
name = "gdk4"

[features]
dox = ["ffi/dox", "glib/dox", "gio/dox", "gdk-pixbuf/dox", "cairo-rs/dox", "pango/dox"]
v4_2 = ["ffi/v4_2"]
v4_4 = ["ffi/v4_4", "v4_2"]
v4_6 = ["ffi/v4_6", "v4_4"]
v4_8 = ["ffi/v4_8", "v4_6"]

[package.metadata.docs.rs]
features = ["dox"]

[dependencies]
bitflags = "1.0"
cairo-rs = {version = "0.15.1", git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.15" }
ffi = {package = "gdk4-sys", path = "./sys", version = "0.4.9"}
gdk-pixbuf = {version = "0.15.1", git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.15" }
gio = {version = "0.15.2", features = ["v2_66"], git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.15"}
glib = {version = "0.15.3", features = ["v2_66"], git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.15"}
libc = "0.2"
pango = {version = "0.15.2", features = ["v1_46"], git = "https://github.com/gtk-rs/gtk-rs-core", branch = "0.15"}

[dev-dependencies]
gir-format-check = "^0.1"
