[options]
girs_directories = ["../gir-files"]
library = "Gdk"
version = "4.0"
min_cfg_version = "4.0.0"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
single_version_file = true
deprecate_by_min_version = true

generate = [
    "Gdk.AnchorHints",
    "Gdk.AxisFlags",
    "Gdk.AxisUse",
    "Gdk.CairoContext",
    "Gdk.CrossingMode",
    "Gdk.DevicePad",
    "Gdk.DevicePadFeature",
    "Gdk.DeviceToolType",
    "Gdk.DragAction",
    "Gdk.DragCancelReason",
    "Gdk.DragSurface",
    "Gdk.EventSequence",
    "Gdk.EventType",
    "Gdk.FrameClock",
    "Gdk.FrameClockPhase",
    "Gdk.FrameTimings",
    "Gdk.FullscreenMode",
    "Gdk.GLError",
    "Gdk.Gravity",
    "Gdk.InputSource",
    "Gdk.KeyMatch",
    "Gdk.MemoryFormat",
    "Gdk.MemoryTexture",
    "Gdk.ModifierType",
    "Gdk.NotifyType",
    "Gdk.Paintable",
    "Gdk.PaintableFlags",
    "Gdk.Popup",
    "Gdk.ScrollDirection",
    "Gdk.SeatCapabilities",
    "Gdk.Snapshot",
    "Gdk.SubpixelLayout",
    "Gdk.SurfaceEdge",
    "Gdk.ToplevelLayout",
    "Gdk.ToplevelState",
    "Gdk.TouchpadGesturePhase",
    "Gdk.VulkanContext",
    "Gdk.VulkanError",
]

manual = [
    "cairo.Content",
    "cairo.Context",
    "cairo.Region",
    "cairo.Surface",
    "Gdk.ButtonEvent",
    "Gdk.CrossingEvent",
    "Gdk.DeleteEvent",
    "Gdk.DNDEvent",
    "Gdk.FocusEvent",
    "Gdk.GrabBrokenEvent",
    "Gdk.KeyEvent",
    "Gdk.KeymapKey",
    "Gdk.MotionEvent",
    "Gdk.PadEvent",
    "Gdk.ProximityEvent",
    "Gdk.Rectangle",
    "Gdk.RGBA",
    "Gdk.ScrollEvent",
    "Gdk.TimeCoord",
    "Gdk.ToplevelSize",
    "Gdk.TouchEvent",
    "Gdk.TouchpadEvent",
    "GdkPixbuf.Pixbuf",
    "Gio.AppLaunchContext",
    "Gio.Cancellable",
    "Gio.File",
    "Gio.Icon",
    "Gio.InputStream",
    "Gio.IOErrorEnum",
    "Gio.ListModel",
    "Gio.OutputStream",
    "GLib.Bytes",
    "GLib.Error",
    "GLib.Priority",
    "GLib.Quark",
    "GLib.String",
    "GObject.Value",
    "Pango.Direction",
    "Pango.Layout",
    "Pango.LayoutLine",
]

[[object]]
name = "Gdk.*"
status = "generate"
    [[object.function]]
    pattern = ".+"
        [[object.function.parameter]]
        name = "cr"
        const = true
        [[object.function.parameter]]
        name = "surface"
        const = true
    [[object.function]]
    pattern = "cairo_.+"
    #manual trait
    ignore = true
    [[object.function]]
    name = "pango_layout_get_clip_region"
    manual = true
    doc_ignore_parameters = ["n_ranges"] 
    [[object.function]]
    name = "pango_layout_line_get_clip_region"
    manual = true
    doc_ignore_parameters = ["n_ranges"] 
    [[object.function]]
    name = "content_register_deserializer"
    manual = true
    [[object.function]]
    name = "content_register_serializer"
    manual = true
    [[object.function]]
    name = "content_serialize_async"
    manual = true # init assert
    [[object.function]]
    name = "content_deserialize_async"
    manual = true
    [[object.function]]
    name = "events_get_angle"
    manual = true # event is a fundemental type
    [[object.function]]
    name = "events_get_center"
    manual = true # event is a fundemental type
    [[object.function]]
    name = "events_get_distance"
    manual = true # event is a fundemental type
    [[object.function]]
    name = "keyval_convert_case"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_from_name"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_is_lower"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_is_upper"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_name"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_to_lower"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_to_unicode"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "keyval_to_upper"
    manual = true # manually handled by keys::Key
    [[object.function]]
    name = "toplevel_size_get_type"
    ignore = true # used directly in gdk::ToplevelSize


[[object]]
name = "Gdk.AppLaunchContext"
status = "generate"
generate_builder = false
final_type = false

[[object]]
name = "Gdk.Clipboard"
status = "generate"
generate_builder = true
    [[object.function]]
    pattern = "set_(value|valist)"
    ignore = true
    [[object.function]]
    name = "set"
    manual = true # use ToValue
    [[object.function]]
    pattern = "(read|read_texture|read_text|read_value|store)_async"
    manual = true # don't enforce Send
    [[object.function]]
    name = "set_content"
        [object.function.return]
        bool_return_is_error = "Can't set new clipboard content"

[[object]]
name = "Gdk.ContentDeserializer"
status = "generate"
    [[object.function]]
    name = "get_input_stream"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_mime_type"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_gtype"
    rename = "type_"
    [[object.function]]
    name = "get_task_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_user_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_value"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "set_task_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_priority"
    manual = true # to use glib::Priority
    [[object.function]]
    name = "return_error"
    manual = true # wrong error mutability

[[object]]
name = "Gdk.ContentFormats"
status = "generate"
    [[object.function]]
    name = "new_for_gtype"
    rename = "for_type"
    [[object.function]]
    name = "contain_gtype"
    rename = "contains_type"
    [[object.function]]
    name = "match_gtype"
    rename = "match_type"
    [[object.function]]
    name = "union_deserialize_gtypes"
    rename = "union_deserialize_types"
    [[object.function]]
    name = "union_serialize_gtypes"
    rename = "union_serialize_types"
    [[object.function]]
    name = "get_gtypes"
    manual = true
    rename = "types"
    [[object.function]]
    name = "get_mime_types"
    manual = true # remove once https://gitlab.gnome.org/GNOME/gtk/-/merge_requests/3488 gets merged
    [[object.function]]
    name = "print"
    manual = true #mutability issue

[[object]]
name = "Gdk.ContentFormatsBuilder"
status = "generate"
    [[object.function]]
    name = "free_to_formats"
    ignore = true # marked skip, redundant with to_formats
    [[object.function]]
    name = "to_formats"
    rename = "build"
    manual = true # renamed, returns non-null, builder-like
    [[object.function]]
    name = "add_gtype"
    manual = true
    rename = "add_type"
    [[object.function]]
    pattern = "add_(mime_type|formats)"
    manual = true

[[object]]
name = "Gdk.ContentProvider"
status = "generate"
manual_traits = ["ContentProviderExtManual"]
    [[object.function]]
    name = "new_typed"
    ignore = true # new_for_value is what the bindings are supposed to use
    [[object.function]]
    name = "get_value"
    manual = true # to return Value
    doc_trait_name = "ContentProviderExtManual"
    [[object.function]]
    name = "ref_formats"
    rename = "formats"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "ref_storable_formats"
    rename = "storable_formats"
        [object.function.return]
        nullable = false
    [[object.property]]
    name = "formats"
    generate = ["notify"] # ignore get/set
    [[object.property]]
    name = "storable-formats"
    generate = ["notify"] # ignore get/set

[[object]]
name = "Gdk.ContentSerializer"
status = "generate"
    [[object.function]]
    name = "get_mime_type"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_output_stream"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_gtype"
    rename = "type_"
    [[object.function]]
    name = "get_task_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_user_data"
    ignore = true # unsafe
    [[object.function]]
    name = "get_value"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "set_task_data"
    ignore = true #unsafe
    [[object.function]]
    name = "get_priority"
    manual = true # to use glib::Priority
    [[object.function]]
    name = "return_error"
    manual = true # wrong error mutability

[[object]]
name = "Gdk.Cursor"
status = "generate"
generate_builder = true

[[object]]
name = "Gdk.Device"
status = "generate"
final_type = false
    [[object.function]]
    name = "get_caps_lock_state"
    rename = "is_caps_locked"
    [[object.function]]
    name = "get_num_lock_state"
    rename = "is_num_locked"
    [[object.function]]
    name = "get_scroll_lock_state"
    rename = "is_scroll_locked"

[[object]]
name = "Gdk.DeviceTool"
status = "generate"
generate_builder = true

[[object]]
name = "Gdk.Display"
status = "generate"
final_type = false
manual_traits = ["DisplayExtManual"]
    [[object.function]]
    name = "get_setting"
    manual = true
    # Actually retrieves the setting in the provided argument
    bypass_auto_rename = true
    [[object.function]]
    name = "get_app_launch_context"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_clipboard"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_default_group"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_default_seat"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_keymap"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_name"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_primary_clipboard"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "get_primary_monitor"
        [object.function.return]
        nullable = false
    [[object.function]]
    name = "translate_key"
    manual = true # to return a Key instead of a u32
    [[object.function]]
    pattern = "map_key(code|val)"
    manual = true # make use of Key
    [[object.function]]
    name = "put_event"
    manual = true # event is a fundemental type

[[object]]
name = "Gdk.DisplayManager"
status = "generate"
generate_builder = false

[[object]]
name = "Gdk.Drag"
status = "generate"
final_type = false

[[object]]
name = "Gdk.DrawContext"
status = "generate"
manual_traits = ["DrawContextExtManual"]
    [[object.function]]
    name = "get_frame_region"
    doc_trait_name = "DrawContextExtManual"
    manual = true

[[object]]
name = "Gdk.Drop"
status = "generate"
    [[object.function]]
    name = "read_async"
    manual = true # const ptr

[[object]]
name = "Gdk.Event"
status = "manual" # fundemental type
final_type = true # avoids the usage of EventExt trait

[[object]]
name = "Gdk.GLContext"
status = "generate"
final_type = false

[[object]]
name = "Gdk.GLTexture"
status = "generate"
    [[object.function]]
    name = "new"
    manual = true

[[object]]
name = "Gdk.Monitor"
status = "generate"
final_type = false
generate_builder = false

[[object]]
name = "Gdk.PopupLayout"
status = "generate"
    [[object.function]]
    name = "get_offset"
    manual = true # invalid mutability

[[object]]
name = "Gdk.Seat"
status = "generate"
final_type = false

[[object]]
name = "Gdk.Surface"
status = "generate"
final_type = false
manual_traits = ["SurfaceExtManual"]
    [[object.function]]
    name = "create_similar_surface"
    manual = true
    doc_trait_name = "SurfaceExtManual"
    [[object.function]]
    name = "set_input_region"
    manual = true #mutability issue
    doc_trait_name = "SurfaceExtManual"
    [[object.function]]
    name = "set_opaque_region"
        [[object.function.parameter]]
        name = "region"
        const = true
    [[object.function]]
    name = "translate_coordinates"
    doc_trait_name = "SurfaceExtManual"
    manual = true # mutability issue

[[object]]
name = "Gdk.Texture"
status = "generate"
manual_traits = ["TextureExtManual"]
    [[object.function]]
    name = "download"
    doc_trait_name = "TextureExtManual"
    manual = true

[[object]]
name = "Gdk.Toplevel"
status = "generate"
manual_traits = ["ToplevelExtManual"]
    [[object.function]]
    name = "inhibit_system_shortcuts"
    manual = true # event is a fundemental type
    doc_trait_name = "ToplevelExtManual"
    [[object.function]]
    name = "show_window_menu"
    manual = true # event is a fundemental type
    doc_trait_name = "ToplevelExtManual"
    [[object.signal]]
    name = "compute-size"
    manual = true
    doc_trait_name = "ToplevelExtManual"
