[options]
work_mode = "sys"
library = "Gdk"
version = "4.0"
min_cfg_version = "4.0.0"
single_version_file = "."
split_build_rs = true
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "GObject",
    "Gio",
    "GdkPixbuf",
    "Pango",
    "Cairo",
]

[[object]]
name = "Gdk.*"
status = "generate"
    [[object.function]]
    name = "drag_surface_size_get_type"
    version = "4.12"

[[object]]
name = "Gdk.MemoryFormat"
status = "generate"
    [[object.member]]
    name = "n_formats"
    alias = true # not useful
