[build-dependencies]
system-deps = "3"

[dependencies]
libc = "0.2"

[dependencies.cairo-sys-rs]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gdk-pixbuf-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gdk4-sys]
path = "../../gdk4/sys"

[dependencies.gio-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.glib-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gobject-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.graphene-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dependencies.gsk4-sys]
path = "../../gsk4/sys"

[dependencies.pango-sys]
git = "https://github.com/gtk-rs/gtk-rs"

[dev-dependencies]
shell-words = "1.0.0"
tempfile = "3"

[features]
dox = []
v4_2 = []

[lib]
name = "gtk4_sys"

[package]
authors = ["The Gtk-rs Project Developers"]
build = "build.rs"
description = "FFI bindings to libgtk-4"
homepage = "http://gtk-rs.org/"
keywords = ["gtk", "gtk4", "ffi", "gtk-rs", "gnome"]
license = "MIT"
links = "gtk-4"
name = "gtk4-sys"
repository = "https://github.com/gtk-rs/sys"
version = "0.1.0"
edition = "2018"
[package.metadata.docs.rs]
features = ["dox"]
[package.metadata.system-deps.gtk4]
name = "gtk4"
version = "4.0.0"

[package.metadata.system-deps.gtk4.v4_2]
version = "4.2"
