[options]
work_mode = "sys"
library = "GdkWin32"
version = "4.0"
min_cfg_version = "4.0.0"
single_version_file = "."
girs_directories = ["../../gir-files"]

external_libraries = [
    "GLib",
    "cairo",
]

[external_libraries]
gdk4 = "Gdk"

[[object]]
name = "GdkWin32.*"
status = "generate"
    [[object.function]]
    name = "d3d12_error_quark"
    version = "4.20"