[book]
authors = ["Julian Hofer"]
language = "en"
src = "src"
title = "GUI development with Rust and GTK 4"


[output.html]
git-repository-url = "https://github.com/gtk-rs/gtk4-rs/tree/main/book"
git-repository-icon = "fab-github"
additional-css = ["theme/style.css"]
additional-js = ["theme/meson.js"]
playground.runnable = false
