[book]
authors = ["Julian Hofer"]
language = "en"
multilingual = false
src = "src"
title = "GUI development with Rust and GTK 4"


[output.html]
default-theme = "Rust"
git-repository-url = "https://github.com/gtk-rs/gtk4-rs/tree/main/book"
git-repository-icon = "fa-github"
additional-css = ["theme/style.css"]
playground.runnable = false
